### PR TITLE
Fix plots on Python 3 and optimize slightly

### PR DESCRIPTION
**Pull request by QuLogic**
Optimizing the interpolation is about 8-10% faster, though of course, most of the time is spent starting and stopping `proj` processes, so it's maybe about 30 s faster out of 6 minutes.

Also, the interpolation did not quite work correctly originally; it did not insure that point distances were actually below the tolerance, so there are a few small differences in the results.

I did not re-create the images, as I assume you'll be redoing stuff when things in OSGeo/proj.4#525 are decided.

### CODE REVIEW

**Comment by kbevers** [comment]
> Also, the interpolation did not quite work correctly originally; it did not insure that point distances were actually below the tolerance, so there are a few small differences in the results.

Can you show an example of this?

**Comment by QuLogic** [comment]
Sure, using [this gist](https://gist.github.com/QuLogic/1d1c3f22634f1c12deb53de748ed9a15):
```
[0, 1, 2, 8, 9, 5, 10]
[  0.    1.    2.    4.    6.    8.    8.    9.    7.    5.    5.    7.5  10. ]
[  0.    1.    2.    4.    6.    8.    9.    7.    5.    6.66666667   8.33333333  10.   ]
```
Between 2 and 8 is correctly filled by 2 (except there's a duplicate 8) and between 9 and 5 is correct (except the duplicate 5 again), but between 5 and 10, the step is 2.5, not 2. I chose to make it _at most_ 2, so it's a little less here at 1⅔.

**Comment by kbevers** [comment]
Thanks, and nice catch. I think your additions improves the code quite a bit, and it is obvious that you have a better grasp of numpy than I do!

I'll give it a closer look later to day and merge when I am sure I understand what's going in on in the changes :-)

**Comment by QuLogic** [comment]
Best to look at the commits individually then, which should be clear(ish).

**Comment by kbevers** [comment]
Finally had the time to look at this. Very good work indeed. I think that are two parts to this, improving overall quality of the code and improving functionality. Would you mind if I squash the first 5 commits into one, and the last three into another commit? I'd like to not clutter the commit history too much if I can help it.

**Comment by QuLogic** [comment]
That sounds reasonable; I'm not sure whether the second commit falls into the first category, though.

**Comment by kbevers** [comment]
Changes applied manually. See the original PR in the PROJ.4 repository.

**Pull request closed without merging**
